[workspace]
resolver = "2"
members = [
  "engine",
  "app",
  ]

[profile.release-with-debug-assertions]
inherits = "release"
debug-assertions = true

[profile.dev-no-debug-assertions]
inherits = "dev"
debug-assertions = false
